import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SideBar from "@/components/sideBar";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Inline top bar for students area */}

        <div className="flex">
          {/* Sidebar fixed on left */}
          <div className="hidden md:block">
            <SideBar />
          </div>
          <Navbar />

          {/* Main content area. Add left margin equal to sidebar width on md+ and top padding for the fixed TopBar */}
          <main className="md:ml-56 w-full">
            <div className="pt-20">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
